version: '3.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4620:4566-4620'
    environment:
      - SERVICES=serverless,cognito,rds,sqs,sns,cloudformation,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
